//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRequester.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebRequester.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0116)http://catalog.mann-filter.com/EU/tur/vehicle/MANN-FILTER%20Katalog%20Europa/Ara%C3%A7lar/Kamyon%20%2B%20Otob%C3%BCs --&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;tr&quot;&gt;&lt;head id=&quot;j_idt2&quot;&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;meta content=&quot;IE=Edge,chrome=1&quot; http-equiv=&quot;X-UA-Compatible&quot;&gt;
        ///	
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, user-scalable=yes&quot;&gt;
        ///	&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;tr&quot;&gt;
        ///	&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MANNFILTER_Araclar_Kamyon_Otobus {
            get {
                return ResourceManager.GetString("MANNFILTER_Araclar_Kamyon_Otobus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0100)http://catalog.mann-filter.com/EU/tur/vehicle/MANN-FILTER%20Katalog%20Europa/Ara%C3%A7lar/Motosiklet --&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;tr&quot;&gt;&lt;head id=&quot;j_idt2&quot;&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;meta content=&quot;IE=Edge,chrome=1&quot; http-equiv=&quot;X-UA-Compatible&quot;&gt;
        ///	
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, user-scalable=yes&quot;&gt;
        ///	&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;tr&quot;&gt;
        ///	&lt;meta http-equiv= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MANNFILTER_Araclar_Motosiklet {
            get {
                return ResourceManager.GetString("MANNFILTER_Araclar_Motosiklet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0123)http://catalog.mann-filter.com/EU/tur/vehicle/MANN-FILTER%20Katalog%20Europa/Ara%C3%A7lar/Off%20Highway%20uygulamalar%C4%B1 --&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;tr&quot;&gt;&lt;head id=&quot;j_idt2&quot;&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;meta content=&quot;IE=Edge,chrome=1&quot; http-equiv=&quot;X-UA-Compatible&quot;&gt;
        ///	
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, user-scalable=yes&quot;&gt;
        ///	&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MANNFILTER_Araclar_Off_Highway_uygulamalari {
            get {
                return ResourceManager.GetString("MANNFILTER_Araclar_Off_Highway_uygulamalari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0131)http://catalog.mann-filter.com/EU/tur/vehicle/MANN-FILTER%20Katalog%20Europa/Ara%C3%A7lar/Otomobiller%20%2B%20Ticari%20Ara%C3%A7lar --&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;tr&quot;&gt;&lt;head id=&quot;j_idt2&quot;&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;meta content=&quot;IE=Edge,chrome=1&quot; http-equiv=&quot;X-UA-Compatible&quot;&gt;
        ///	
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, user-scalable=yes&quot;&gt;
        ///	&lt;meta http-equiv=&quot;Content-Language&quot; c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MANNFILTER_Araclar_Otomobiller_Ticari_Araclar {
            get {
                return ResourceManager.GetString("MANNFILTER_Araclar_Otomobiller_Ticari_Araclar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0089)http://catalog.mann-filter.com/EU/tur/vehicle/MANN-FILTER%20Katalog%20Europa/Ara%C3%A7lar --&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;tr&quot;&gt;&lt;head id=&quot;j_idt2&quot;&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;meta content=&quot;IE=Edge,chrome=1&quot; http-equiv=&quot;X-UA-Compatible&quot;&gt;
        ///	
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, user-scalable=yes&quot;&gt;
        ///	&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;tr&quot;&gt;
        ///	&lt;meta http-equiv=&quot;pragma&quot; co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mannfilter_initial_page {
            get {
                return ResourceManager.GetString("mannfilter_initial_page", resourceCulture);
            }
        }
    }
}
